name: Build & Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  all:
    uses: NetEvolve/pipelines/.github/workflows/cicd-dotnet.yml@main
    with:
      version-dotnet: 7.x
      solution: $GITHUB_WORKSPACE/Extensions.Test.sln
    secrets: inherit
