name: Build & Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  all:
    uses: NetEvolve/pipelines/.github/workflows/cicd-dotnet.yml@fix/nuget-restore
    with:
      version-dotnet: 7.x
      solution: ./Extensions.Test.sln
    secrets: inherit
